name: thuvienapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- CÁC THƯ VIỆN CŨ ---
  fl_chart: ^0.63.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  intl: ^0.19.0

  # --- CÁC THƯ VIỆN MỚI (AI & ENV) ---
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Khai báo assets để load file .env
  assets:
    - .env
    # - assets/images/ (Nếu bạn có ảnh thì bỏ comment dòng này)